### ISSUE TITLE
Make all the data_grabber get_data() functions consistent

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#11]
All get_data() functions should have the same parameters:

start_date
end_date
variables=[]
return_df=False (return the dict with separate Series by default, merge all dicts into a df if return_df is true)
-- This should be a function in lib.py
remove_nas=True

Others?

**Comment by n-beckage** [comment]
Note to self (and others): get_data() fcns are found in [usgs_obs.py](https://github.com/CIROH-UVM/forecast-workflow/blob/main/data/usgs_obs.py), [nwm_forecast.py](https://github.com/CIROH-UVM/forecast-workflow/blob/main/data/nwm_forecast.py), [gfs_download_fcns.py](https://github.com/CIROH-UVM/forecast-workflow/blob/main/data/gfs_download_fcns.py), [colchester_reef_met.py](https://github.com/CIROH-UVM/forecast-workflow/blob/main/data/colchester_reef_met.py), and [btv_met.py](https://github.com/CIROH-UVM/forecast-workflow/blob/main/data/btv_met.py)
