### ISSUE TITLE
Clean up download verbosity so it's log compatible

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#13]
RIght now, we have curl running with --silent, but now, we get no feedback on the download status.

Maybe we need a different download tool, or just need change the command line option to --progress-bar, but the log / sysout should give us a progress without generating a ridiculously long printed log for each file.

At a minimum... standardize the code for downloading the GFS and NWM forecasts (maybe put in lib.py).  And for now, use the sh module for curl.  Or, honestly have both use Noah's subprocess code.  Just make them the same... but it seems using the sh module will give us a big more options and functionality for other terminal commands?

**Comment by n-beckage** [comment]
Fixed with commit [#59fee6b](https://github.com/CIROH-UVM/forecast-workflow/commit/59fee6bc1f9de560f2f92b005d6c40cf77aae829)
