### ISSUE TITLE
Reduce size of GFS gribs after downloads by grabbing NE US lat-lon window

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#20]

**Comment by pclemins** [comment]
Potential tools to help out:

GRIB2 Utilities
https://www.cpc.ncep.noaa.gov/products/wesley/
https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/index.html

**Comment by n-beckage** [comment]
See commit [#03104cf](https://github.com/CIROH-UVM/forecast-workflow/commit/03104cf8b9594dc722ddac91119ddc9a6bf1298b)
