### ISSUE TITLE
Revise 7dayforecast script to send emails only on final completion of forecast or at failures in the workflow

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#25]
I see two ways of sending on failure:

1) In bash: Look at the return code of each line that executes part of the workflow.  If not 0, send email about failure with the tail of the log in the email body so we can see what the failure was.  Not sure how to, or if we can, get the return code of jobs in bash

2) More to python... use sh to call the parts of the workflow and then look at the return code.  There's a built-in python module to send mail.  We'll have to test that and make sure it works.

**Comment by n-beckage** [comment]
We have some code to do this in a bash script but not in the repo:

```shell
# this should send us an email if the model DOESN'T work
if captured=$(python -m models.aem3d.AEM3D_prep_worker --fc_start $FCDATE --old_dirs 2>&1); then
    # exit code is 0 if script module ran without error
	pythonresult=0

	mail -s "TEST SUCCESS: prep_worker Complete" \
	noah.beckage@uvm.edu \
	patrick.clemins@uvm.edu \
	<<< "$(tail -50 .log)"

else
    # exit code will be 1 if model ran with error
    pythonresult=$?
    
	mail -s "TEST FAILURE: prep_worker Failed" \
	noah.beckage@uvm.edu \
	patrick.clemins@uvm.edu \
	<<< "ERROR: $captured"
fi
``` 

As of our last production tag, we decided not to implement this change. But, it's here if we ever need it. See `/data/users/n/b/nbeckage/forecastScripts/productionTest.sh` on the vm for the full script.
