### ISSUE TITLE
Remove raw_fc_data from forecastData/gfs/raw_fc_data/gfs.date path

### ISSUE THREAD

**Issue by pclemins** [CIROH-UVM/forecast-workflow#7]
Rewrite code to download daily GFS forecast to just forecastData/gfs/gfs.date, removing the raw_fc_data directory.

Then, need to update AEM3D_prep to look in the right spot for the forecast files as well.

Might need to update the forecast.sh and associate .py files.

**Comment by n-beckage** [comment]
Fixed with commit [#03104cf](https://github.com/CIROH-UVM/forecast-workflow/commit/03104cf8b9594dc722ddac91119ddc9a6bf1298b)
